version: '3'

services:
  front :
    build: front-end/.
    image: front
    container_name: frontc
    ports:
      - "80:80"
  
  gate :
    build: back-end/APIGateway/.
    image: apigate
    container_name: gatec
    ports:
      - "4000:80"
    links:
      - dbops
      - login
      - dlder
      - picturenfs

  db-entomo :
    build: back-end/Database/.
    image: postgres
    container_name: db-entomoc
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - DataEntomo:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres

  db-login :
    build: back-end/Database/.
    image: postgres
    container_name: db-loginc
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - DataLogin:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres


  dbops :
    build: back-end/DBOps/.
    image: dbops
    container_name: dbopsc
    ports:
      - "4001:80"
    links:
      - db-entomo
    depends_on:
      db-entomo:
        condition: service_healthy

  dlder :
    build: back-end/FileDownloader/.
    image: dlder
    container_name: dlderc
    ports:
      - "4002:80"

  login :
    build: back-end/Login/.
    image: login
    container_name: loginc
    ports:
      - "4003:80"
    links:
      - db-login
    depends_on:
      db-login:
        condition: service_healthy

  picturenfs :
    build: back-end/PictureNFS/.
    image: picturenfs
    conatiner_name: picturenfsc
    ports: "4004:80"
    volumes:
      - Pictures:/usr/picturenfs/share
    
volumes:
  DataEntomo:
  DataLogin:
  Pictures:
